#!/usr/bin/env bash
# Install nginx on web server, listening on port 80

sudo apt-get update -y && sudo apt-get install nginx -y
sudo ufw allow 'Nginx HTTP' && echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
